const DEMO_ASSESSMENT_INSTANCE_ID = 11;

const DEMO_CATEGORIES = [
  {
    category_id: 1,
    category_key: 'anthropometry',
    display_name: 'Anthropometry',
    assessment_instance_id: DEMO_ASSESSMENT_INSTANCE_ID,
    status: 'active',
    routeId: 'anthropometry',
  },
  {
    category_id: 2,
    category_key: 'family_history',
    display_name: 'Family History',
    assessment_instance_id: DEMO_ASSESSMENT_INSTANCE_ID,
    status: 'active',
    routeId: 'family-history',
  },
  {
    category_id: 3,
    category_key: 'lifestyle_habits',
    display_name: 'Lifestyle and Habits',
    assessment_instance_id: DEMO_ASSESSMENT_INSTANCE_ID,
    status: 'active',
    routeId: 'lifestyle-habits',
  },
  {
    category_id: 4,
    category_key: 'nutrition_log',
    display_name: 'Nutrition Log',
    assessment_instance_id: DEMO_ASSESSMENT_INSTANCE_ID,
    status: 'active',
    routeId: 'nutrition-log',
  },
  {
    category_id: 5,
    category_key: 'vitals',
    display_name: 'Vitals',
    assessment_instance_id: DEMO_ASSESSMENT_INSTANCE_ID,
    status: 'active',
    routeId: 'vitals',
  },
];

const DEMO_ANTHROPOMETRY_QUESTIONS = [
  {
    question_id: 1,
    question_text: 'What is your height?',
    question_type: 'number',
    question_key: 'height',
    category_id: 1,
    is_required: true,
    options: null,
    answer: null,
  },
  {
    question_id: 2,
    question_text: 'What is your body weight?',
    question_type: 'number',
    question_key: 'weight',
    category_id: 1,
    is_required: true,
    options: null,
    answer: null,
  },
  {
    question_id: 3,
    question_text: 'What is your waist size?',
    question_type: 'number',
    question_key: 'waist_circumference',
    category_id: 1,
    is_required: true,
    options: null,
    answer: null,
  },
  {
    question_id: 4,
    question_text: 'What is your hip size?',
    question_type: 'number',
    question_key: 'hip_circumference',
    category_id: 1,
    is_required: false,
    options: null,
    answer: null,
  },
  {
    question_id: 5,
    question_text: 'What is your body fat percentage?',
    question_type: 'number',
    question_key: 'body_fat_percentage',
    category_id: 1,
    is_required: false,
    options: null,
    answer: null,
  },
];

export const DEMO_FAMILY_HISTORY_QUESTIONS = [
  {
    question_id: 6,
    question_text: 'Where have you lived most of your life?',
    question_type: 'single_choice',
    question_key: 'living_region',
    category_id: 2,
    is_required: true,
    is_read_only: false,
    help_text: 'Select the environment you lived in most',
    options: [
      { option_value: 'inland', display_name: 'Inland', tooltip_text: null },
      { option_value: 'coastal', display_name: 'Coastal', tooltip_text: null },
    ],
    answer: null,
  },
  {
    question_id: 7,
    question_text: 'Do any of your close blood relatives have the following health conditions?',
    question_type: 'multiple_choice',
    question_key: 'family_health_history',
    category_id: 2,
    is_required: true,
    is_read_only: false,
    help_text: 'Select multiple or None',
    options: [
      { option_value: 'type_2_diabetes', display_name: 'Type 2 Diabetes', tooltip_text: null },
      { option_value: 'hypertension', display_name: 'Hypertension', tooltip_text: null },
      { option_value: 'fatty_liver', display_name: 'Fatty Liver', tooltip_text: null },
      { option_value: 'lipid_disorders', display_name: 'Lipid Disorders', tooltip_text: null },
      { option_value: 'heart_ailments', display_name: 'Heart Ailments', tooltip_text: null },
      { option_value: 'thyroid_disorders', display_name: 'Thyroid Disorders', tooltip_text: null },
      { option_value: 'pcos', display_name: 'PCOS', tooltip_text: null },
      { option_value: 'stroke', display_name: 'Stroke', tooltip_text: null },
      { option_value: 'mental_health', display_name: 'Mental Health', tooltip_text: null },
      { option_value: 'other', display_name: 'Other', tooltip_text: null },
      { option_value: 'none', display_name: 'None', tooltip_text: null },
    ],
    answer: null,
  },
  {
    question_id: 8,
    question_text: 'Are you diagnosed with the following diseases?',
    question_type: 'multiple_choice',
    question_key: 'diagnosed_diseases',
    category_id: 2,
    is_required: true,
    is_read_only: false,
    help_text: 'Select multiple or None',
    options: [
      { option_value: 'type_2_diabetes', display_name: 'Type 2 Diabetes', tooltip_text: null },
      { option_value: 'hypertension', display_name: 'Hypertension', tooltip_text: null },
      { option_value: 'fatty_liver', display_name: 'Fatty Liver', tooltip_text: null },
      { option_value: 'lipid_disorders', display_name: 'Lipid Disorders', tooltip_text: null },
      { option_value: 'heart_ailments', display_name: 'Heart Ailments', tooltip_text: null },
      { option_value: 'thyroid_disorders', display_name: 'Thyroid Disorders', tooltip_text: null },
      { option_value: 'pcos', display_name: 'PCOS', tooltip_text: null },
      { option_value: 'stroke', display_name: 'Stroke', tooltip_text: null },
      { option_value: 'mental_health', display_name: 'Mental Health', tooltip_text: null },
      { option_value: 'other', display_name: 'Other', tooltip_text: null },
      { option_value: 'none', display_name: 'None', tooltip_text: null },
    ],
    answer: null,
  },
  {
    question_id: 9,
    question_text: 'Are you taking medications for the following diseases?',
    question_type: 'multiple_choice',
    question_key: 'diagnosed_diseases_medications',
    category_id: 2,
    is_required: false,
    is_read_only: false,
    help_text: 'Select multiple or None',
    options: [
      { option_value: 'type_2_diabetes', display_name: 'Type 2 Diabetes', tooltip_text: null },
      { option_value: 'hypertension', display_name: 'Hypertension', tooltip_text: null },
      { option_value: 'fatty_liver', display_name: 'Fatty Liver', tooltip_text: null },
      { option_value: 'lipid_disorders', display_name: 'Lipid Disorders', tooltip_text: null },
      { option_value: 'heart_ailments', display_name: 'Heart Ailments', tooltip_text: null },
      { option_value: 'thyroid_disorders', display_name: 'Thyroid Disorders', tooltip_text: null },
      { option_value: 'pcos', display_name: 'PCOS', tooltip_text: null },
      { option_value: 'stroke', display_name: 'Stroke', tooltip_text: null },
      { option_value: 'mental_health', display_name: 'Mental Health', tooltip_text: null },
      { option_value: 'other', display_name: 'Other', tooltip_text: null },
      { option_value: 'none', display_name: 'None', tooltip_text: null },
    ],
    answer: null,
  },
  {
    question_id: 10,
    question_text: 'Family health history (other)',
    question_type: 'text',
    question_key: 'family_health_history_other',
    category_id: 2,
    is_required: false,
    is_read_only: false,
    help_text: null,
    options: null,
    answer: null,
  },
  {
    question_id: 11,
    question_text: 'Diagnosed diseases (other)',
    question_type: 'text',
    question_key: 'diagnosed_diseases_other',
    category_id: 2,
    is_required: false,
    is_read_only: false,
    help_text: null,
    options: null,
    answer: null,
  },
  {
    question_id: 12,
    question_text: 'Medications (other)',
    question_type: 'text',
    question_key: 'diagnosed_diseases_medications_other',
    category_id: 2,
    is_required: false,
    is_read_only: false,
    help_text: null,
    options: null,
    answer: null,
  },
];

export const DEMO_LIFESTYLE_HABITS_QUESTIONS = [
  {
    question_id: 13,
    question_text: 'How long do you sit continuously every day due to work or lifestyle?',
    question_type: 'single_choice',
    question_key: 'sitting_hours',
    category_id: 3,
    is_required: true,
    is_read_only: false,
    help_text: null,
    options: [
      { option_value: 'lt_1_hr', display_name: 'Less than 1 hour', tooltip_text: null },
      { option_value: '1_4_hr', display_name: '1-4 hours', tooltip_text: null },
      { option_value: 'gt_4_hr', display_name: 'More than 4 hours', tooltip_text: null },
    ],
    answer: null,
  },
  {
    question_id: 14,
    question_text: 'How much time do you spend engaging in physical activity or exercise daily?',
    question_type: 'single_choice',
    question_key: 'physical_activity_frequency',
    category_id: 3,
    is_required: true,
    is_read_only: false,
    help_text: null,
    options: [
      { option_value: 'lt_30_min', display_name: 'Less than 30 minutes a day', tooltip_text: null },
      { option_value: '30_60_min', display_name: '30-60 minutes a day', tooltip_text: null },
      { option_value: 'gt_60_min', display_name: 'More than 60 minutes a day', tooltip_text: null },
      { option_value: 'rarely', display_name: 'Rarely or never', tooltip_text: null },
    ],
    answer: null,
  },
  {
    question_id: 15,
    question_text: 'On a typical week, how much time do you dedicate to leisure activities, workouts or sports?',
    question_type: 'single_choice',
    question_key: 'exercise_frequency_week',
    category_id: 3,
    is_required: true,
    is_read_only: false,
    help_text: null,
    options: [
      { option_value: 'lt_1_hr', display_name: 'Less than 1 hour', tooltip_text: null },
      { option_value: '1_3_hr', display_name: '1-3 hours', tooltip_text: null },
      { option_value: '4_8_hr', display_name: '4-8 hours', tooltip_text: null },
      { option_value: 'gt_8_hr', display_name: 'More than 8 hours', tooltip_text: null },
      { option_value: 'rarely', display_name: 'Rarely or never', tooltip_text: null },
    ],
    answer: null,
  },
  {
    question_id: 16,
    question_text: 'On an average week, how would you rate the intensity of your activities or workouts?',
    question_type: 'single_choice',
    question_key: 'exercise_level',
    category_id: 3,
    is_required: true,
    is_read_only: false,
    help_text: 'Low, Moderate, High intensity based on effort',
    options: [
      { option_value: 'low', display_name: 'Low intensity', tooltip_text: null },
      { option_value: 'moderate', display_name: 'Moderate intensity', tooltip_text: null },
      { option_value: 'high', display_name: 'High intensity', tooltip_text: null },
    ],
    answer: null,
  },
  {
    question_id: 17,
    question_text: 'How much time do you spend actively walking each day?',
    question_type: 'single_choice',
    question_key: 'local_walking_time',
    category_id: 3,
    is_required: true,
    is_read_only: false,
    help_text: null,
    options: [
      { option_value: 'lt_15_min', display_name: 'Less than 15 mins', tooltip_text: null },
      { option_value: '15_30_min', display_name: '15-30 mins', tooltip_text: null },
      { option_value: '30_60_min', display_name: '30-60 mins', tooltip_text: null },
      { option_value: '1_2_hr', display_name: '1-2 hours', tooltip_text: null },
      { option_value: 'gt_2_hr', display_name: 'More than 2 hours', tooltip_text: null },
    ],
    answer: null,
  },
  {
    question_id: 18,
    question_text: 'What is your average duration of good-quality sleep?',
    question_type: 'single_choice',
    question_key: 'sleeping_hours',
    category_id: 3,
    is_required: true,
    is_read_only: false,
    help_text: null,
    options: [
      { option_value: 'lt_5_hr', display_name: 'Less than 5 hours', tooltip_text: null },
      { option_value: '5_7_hr', display_name: 'Between 5-7 hours', tooltip_text: null },
      { option_value: '7_9_hr', display_name: 'Between 7-9 hours', tooltip_text: null },
      { option_value: 'gt_9_hr', display_name: 'More than 9 hours', tooltip_text: null },
    ],
    answer: null,
  },
  {
    question_id: 19,
    question_text: 'What is your alcohol consumption?',
    question_type: 'single_choice',
    question_key: 'alcohol_frequency',
    category_id: 3,
    is_required: false,
    is_read_only: false,
    help_text: null,
    options: [
      { option_value: 'none', display_name: 'I do not drink alcohol', tooltip_text: null },
      { option_value: 'quit', display_name: 'I quit alcohol', tooltip_text: null },
      { option_value: '1_2_6m', display_name: '1-2 times in 6 months', tooltip_text: null },
      { option_value: '1_2_3m', display_name: '1-2 times in 3 months', tooltip_text: null },
      { option_value: '3_per_week', display_name: '3 servings per week or less', tooltip_text: null },
      { option_value: 'gt_3_week', display_name: 'More than 3 servings per week', tooltip_text: null },
    ],
    answer: null,
  },
  {
    question_id: 20,
    question_text: 'How often do you smoke cigarettes or tobacco?',
    question_type: 'single_choice',
    question_key: 'tobacco_frequency',
    category_id: 3,
    is_required: false,
    is_read_only: false,
    help_text: null,
    options: [
      { option_value: 'none', display_name: 'I do not smoke', tooltip_text: null },
      { option_value: 'quit', display_name: 'I quit smoking', tooltip_text: null },
      { option_value: '1_2_month', display_name: '1-2 times a month', tooltip_text: null },
      { option_value: '1_3_week', display_name: '1-3 times a week', tooltip_text: null },
      { option_value: '4_5_week', display_name: '4-5 times a week', tooltip_text: null },
      { option_value: '5_7_week', display_name: '5-7 times a week', tooltip_text: null },
      { option_value: 'gt_7_week', display_name: 'More than 7 times a week', tooltip_text: null },
    ],
    answer: null,
  },
  {
    question_id: 21,
    question_text: 'What are your primary health and wellness priorities?',
    question_type: 'multiple_choice',
    question_key: 'health_priorities',
    category_id: 3,
    is_required: true,
    is_read_only: false,
    help_text: 'Choose top 2 priorities',
    options: [
      { option_value: 'weight_loss', display_name: 'Weight Loss', tooltip_text: null },
      { option_value: 'muscle_gain', display_name: 'Building Muscle Mass', tooltip_text: null },
      { option_value: 'metabolic_health', display_name: 'Improving Metabolic Health', tooltip_text: null },
      { option_value: 'energy', display_name: 'Increase Energy Levels', tooltip_text: null },
      { option_value: 'endurance', display_name: 'Improving Physical Endurance', tooltip_text: null },
      { option_value: 'strength', display_name: 'Increasing Strength', tooltip_text: null },
    ],
    answer: null,
  },
  {
    question_id: 22,
    question_text: 'What aspect of your lifestyle changes would you like to prioritize?',
    question_type: 'single_choice',
    question_key: 'goal_preference',
    category_id: 3,
    is_required: true,
    is_read_only: false,
    help_text: null,
    options: [
      { option_value: 'diet', display_name: 'Reducing daily diet intake', tooltip_text: null },
      { option_value: 'habits', display_name: 'Forming healthy habits', tooltip_text: null },
      { option_value: 'activity', display_name: 'Increasing physical activity', tooltip_text: null },
    ],
    answer: null,
  },
];

export const DEMO_NUTRITION_LOG_QUESTIONS = [
  {
    question_id: 23,
    question_text: 'What type of diet do you primarily consume?',
    question_type: 'single_choice',
    question_key: 'diet_preference',
    category_id: 4,
    is_required: true,
    is_read_only: false,
    help_text: null,
    options: [
      { option_value: 'veg', display_name: 'Veg', tooltip_text: null },
      { option_value: 'non_veg', display_name: 'Non-Veg', tooltip_text: null },
      { option_value: 'eggetarian', display_name: 'Eggetarian', tooltip_text: null },
      { option_value: 'jain', display_name: 'Jain', tooltip_text: null },
      { option_value: 'flexitarian', display_name: 'Flexitarian', tooltip_text: null },
      { option_value: 'pescatarian', display_name: 'Pescatarian', tooltip_text: null },
    ],
    answer: null,
  },
  {
    question_id: 24,
    question_text: 'Which of the following food groups do you consume every day?',
    question_type: 'multiple_choice',
    question_key: 'food_groups',
    category_id: 4,
    is_required: true,
    is_read_only: false,
    help_text: null,
    options: [
      { option_value: 'pulses', display_name: 'Pulses / Legumes', tooltip_text: null },
      { option_value: 'fruits', display_name: 'Fresh Fruits', tooltip_text: null },
      { option_value: 'vegetables', display_name: 'Fresh Vegetables', tooltip_text: null },
      { option_value: 'nuts', display_name: 'Nuts / Seeds', tooltip_text: null },
      { option_value: 'grains', display_name: 'Whole Grains', tooltip_text: null },
      { option_value: 'eggs', display_name: 'Eggs', tooltip_text: null },
      { option_value: 'milk', display_name: 'Milk / Curd', tooltip_text: null },
      { option_value: 'chicken_fish', display_name: 'Chicken / Fish', tooltip_text: null },
      { option_value: 'cruciferous', display_name: 'Cruciferous Vegetables', tooltip_text: null },
      { option_value: 'none', display_name: 'None', tooltip_text: null },
    ],
    answer: null,
  },
  {
    question_id: 25,
    question_text: 'How frequently do you have a healthy homemade breakfast in a week?',
    question_type: 'single_choice',
    question_key: 'healthy_breakfast_frequency',
    category_id: 4,
    is_required: true,
    is_read_only: false,
    help_text: null,
    options: [
      { option_value: 'gt_5', display_name: 'More than 5 times', tooltip_text: null },
      { option_value: 'lt_5', display_name: 'Less than 5 times', tooltip_text: null },
      { option_value: 'none', display_name: 'Do not have breakfast', tooltip_text: null },
    ],
    answer: null,
  },
  {
    question_id: 26,
    question_text: 'How frequently do you consume fresh fruits?',
    question_type: 'single_choice',
    question_key: 'fresh_fruit_frequency',
    category_id: 4,
    is_required: true,
    is_read_only: false,
    help_text: null,
    options: [
      { option_value: 'daily_1_2', display_name: '1-2 times per day', tooltip_text: null },
      { option_value: 'weekly_2_3', display_name: '2-3 times a week', tooltip_text: null },
      { option_value: 'weekly_1', display_name: 'Once a week or less', tooltip_text: null },
      { option_value: 'rare', display_name: 'Rarely or never', tooltip_text: null },
      { option_value: 'monthly', display_name: '1-2 times per month', tooltip_text: null },
    ],
    answer: null,
  },
  {
    question_id: 27,
    question_text: 'How frequently do you consume cookies, biscuits, bread, or cakes?',
    question_type: 'single_choice',
    question_key: 'baked_goods_frequency',
    category_id: 4,
    is_required: true,
    is_read_only: false,
    help_text: null,
    options: [
      { option_value: 'weekly_1', display_name: 'Once a week or less', tooltip_text: null },
      { option_value: 'weekly_2_3', display_name: '2-3 times a week', tooltip_text: null },
      { option_value: 'gt_4_week', display_name: '4 or more times a week', tooltip_text: null },
      { option_value: 'rare', display_name: 'Rarely or never', tooltip_text: null },
      { option_value: 'monthly', display_name: '1-2 times per month', tooltip_text: null },
    ],
    answer: null,
  },
  {
    question_id: 28,
    question_text: 'How frequently do you consume fresh vegetables?',
    question_type: 'single_choice',
    question_key: 'fresh_vegetable_frequency',
    category_id: 4,
    is_required: true,
    is_read_only: false,
    help_text: null,
    options: [
      { option_value: 'daily_1_2', display_name: '1-2 times per day', tooltip_text: null },
      { option_value: 'weekly_2_3', display_name: '2-3 times a week', tooltip_text: null },
      { option_value: 'weekly_1', display_name: 'Once a week or less', tooltip_text: null },
      { option_value: 'rare', display_name: 'Rarely or never', tooltip_text: null },
      { option_value: 'monthly', display_name: '1-2 times per month', tooltip_text: null },
    ],
    answer: null,
  },
  {
    question_id: 29,
    question_text: 'How frequently do you consume sugary drinks and desserts?',
    question_type: 'single_choice',
    question_key: 'dessert_frequency',
    category_id: 4,
    is_required: true,
    is_read_only: false,
    help_text: null,
    options: [
      { option_value: 'daily', display_name: '1-2 times per day', tooltip_text: null },
      { option_value: 'weekly_2_3', display_name: '2-3 times a week', tooltip_text: null },
      { option_value: 'gt_4_week', display_name: '4 or more times a week', tooltip_text: null },
      { option_value: 'rare', display_name: 'Rarely or never', tooltip_text: null },
      { option_value: 'monthly', display_name: '1-2 times per month', tooltip_text: null },
    ],
    answer: null,
  },
  {
    question_id: 30,
    question_text: 'Do you use iodized salt in your diet?',
    question_type: 'single_choice',
    question_key: 'iodized_salt_status',
    category_id: 4,
    is_required: true,
    is_read_only: false,
    help_text: null,
    options: [
      { option_value: 'yes', display_name: 'Yes', tooltip_text: null },
      { option_value: 'no', display_name: 'No', tooltip_text: null },
    ],
    answer: null,
  },
  {
    question_id: 31,
    question_text: 'How often do you add extra salt to your food?',
    question_type: 'single_choice',
    question_key: 'extra_salt_frequency',
    category_id: 4,
    is_required: true,
    is_read_only: false,
    help_text: null,
    options: [
      { option_value: 'never', display_name: 'Never', tooltip_text: null },
      { option_value: 'rarely', display_name: 'Rarely', tooltip_text: null },
      { option_value: 'usually', display_name: 'Usually', tooltip_text: null },
    ],
    answer: 'rarely',
  },
  {
    question_id: 32,
    question_text: "What's your coffee or tea intake?",
    question_type: 'single_choice',
    question_key: 'caffeine_frequency',
    category_id: 4,
    is_required: false,
    is_read_only: false,
    help_text: null,
    options: [
      { option_value: 'none', display_name: 'I do not drink coffee or tea', tooltip_text: null },
      { option_value: '0_1_day', display_name: '0-1 cups per day', tooltip_text: null },
      { option_value: '1_2_day', display_name: '1-2 cups per day', tooltip_text: null },
      { option_value: 'gt_2_day', display_name: 'More than 2 cups per day', tooltip_text: null },
      { option_value: 'weekly', display_name: '2-3 times a week', tooltip_text: null },
    ],
    answer: null,
  },
  {
    question_id: 33,
    question_text: 'What type of coffee or tea do you drink?',
    question_type: 'multiple_choice',
    question_key: 'caffeine_type',
    category_id: 4,
    is_required: false,
    is_read_only: false,
    help_text: null,
    options: [
      { option_value: 'tea_milk_sugar', display_name: 'Tea with sugar & milk', tooltip_text: null },
      { option_value: 'green_tea', display_name: 'Green tea', tooltip_text: null },
      { option_value: 'coffee_milk_sugar', display_name: 'Coffee with sugar & milk', tooltip_text: null },
      { option_value: 'milk_tea_no_sugar', display_name: 'Milk tea without sugar', tooltip_text: null },
      { option_value: 'black_coffee', display_name: 'Black coffee', tooltip_text: null },
      { option_value: 'black_tea', display_name: 'Black tea', tooltip_text: null },
      { option_value: 'milk_coffee_no_sugar', display_name: 'Milk coffee without sugar', tooltip_text: null },
    ],
    answer: null,
  },
  {
    question_id: 34,
    question_text: 'How frequently do you indulge in dishes rich in butter?',
    question_type: 'single_choice',
    question_key: 'butter_dish_frequency',
    category_id: 4,
    is_required: true,
    is_read_only: false,
    help_text: null,
    options: [
      { option_value: 'weekly_1', display_name: 'Once a week or less', tooltip_text: null },
      { option_value: 'weekly_2_3', display_name: '2-3 times a week', tooltip_text: null },
      { option_value: 'gt_4_week', display_name: '4 or more times a week', tooltip_text: null },
      { option_value: 'rare', display_name: 'Rarely or never', tooltip_text: null },
      { option_value: 'monthly', display_name: '1-2 times per month', tooltip_text: null },
    ],
    answer: null,
  },
  {
    question_id: 35,
    question_text: 'How frequently do you consume red meat?',
    question_type: 'single_choice',
    question_key: 'red_meat_frequency',
    category_id: 4,
    is_required: true,
    is_read_only: false,
    help_text: null,
    options: [
      { option_value: 'weekly_1', display_name: 'Once a week or less', tooltip_text: null },
      { option_value: 'weekly_2_3', display_name: '2-3 times a week', tooltip_text: null },
      { option_value: 'gt_4_week', display_name: '4 or more times a week', tooltip_text: null },
      { option_value: 'rare', display_name: 'Rarely or never', tooltip_text: null },
      { option_value: 'monthly', display_name: '1-2 times per month', tooltip_text: null },
    ],
    answer: null,
  },
  {
    question_id: 36,
    question_text: 'How many glasses of water do you drink in a day?',
    question_type: 'single_choice',
    question_key: 'water_intake_frequency',
    category_id: 4,
    is_required: true,
    is_read_only: false,
    help_text: null,
    options: [
      { option_value: 'lt_2', display_name: 'Less than 2 glasses', tooltip_text: null },
      { option_value: '2', display_name: '2 glasses', tooltip_text: null },
      { option_value: '4', display_name: '4 glasses', tooltip_text: null },
      { option_value: '6', display_name: '6 glasses', tooltip_text: null },
      { option_value: '8', display_name: '8 glasses', tooltip_text: null },
      { option_value: 'gt_8', display_name: 'More than 8 glasses', tooltip_text: null },
    ],
    answer: null,
  },
  {
    question_id: 37,
    question_text: 'How often do you fall sick in a year?',
    question_type: 'single_choice',
    question_key: 'sickness_frequency',
    category_id: 4,
    is_required: true,
    is_read_only: false,
    help_text: null,
    options: [
      { option_value: 'rare', display_name: 'Rarely or Never', tooltip_text: null },
      { option_value: '1_2', display_name: '1 to 2 times', tooltip_text: null },
      { option_value: '2_3', display_name: '2 to 3 times', tooltip_text: null },
      { option_value: '4_5', display_name: '4 to 5 times', tooltip_text: null },
      { option_value: 'gt_6', display_name: 'More than 6 times', tooltip_text: null },
    ],
    answer: null,
  },
];

const DEMO_VITALS_QUESTIONS = [
  {
    question_id: 38,
    question_text: 'Systolic Blood Pressure',
    question_type: 'number',
    question_key: 'systolic_blood_pressure',
    category_id: 5,
    is_required: false,
    options: null,
    answer: null,
  },
  {
    question_id: 39,
    question_text: 'Diastolic Blood Pressure',
    question_type: 'number',
    question_key: 'diastolic_blood_pressure',
    category_id: 5,
    is_required: false,
    options: null,
    answer: null,
  },
];

export const getQuestionnaireDemoContext = () => {
  const questionsByCategoryId = {
    '1': DEMO_ANTHROPOMETRY_QUESTIONS,
    '2': DEMO_FAMILY_HISTORY_QUESTIONS,
    '3': DEMO_LIFESTYLE_HABITS_QUESTIONS,
    '4': DEMO_NUTRITION_LOG_QUESTIONS,
    '5': DEMO_VITALS_QUESTIONS,
  };

  return {
    assessment: {
      assessment_instance_id: DEMO_ASSESSMENT_INSTANCE_ID,
      status: 'active',
    },
    categories: DEMO_CATEGORIES,
    questionsByCategoryId,
  };
};
