export const DEMO_RISK_ANALYSIS_RESPONSE = {
  data: {
    assessment_id: 11,
    metabolic_score: 25.0,
    diseases: [
      { code: 'oxidative_stress', name: 'Oxidative Stress', risk_score_scaled: 27 },
      { code: 'pcos', name: 'PCOS', risk_score_scaled: 46 },
      { code: 'hypertension', name: 'Hypertension', risk_score_scaled: 16 },
      { code: 'nafld', name: 'NAFLD', risk_score_scaled: 49 },
      { code: 'cardiac_health', name: 'Cardiac Health', risk_score_scaled: 12 },
      { code: 'thyroid_health', name: 'Thyroid Health', risk_score_scaled: 12 },
      { code: 'dyslipidemia', name: 'Dyslipidemia', risk_score_scaled: 21 },
      { code: 'diabetes', name: 'Type 2 diabetes', risk_score_scaled: 14 },
      { code: 'obesity', name: 'Obesity', risk_score_scaled: 12 },
    ],
  },
  meta: {},
};

export const DEMO_RISK_ANALYSIS_DETAILS_BY_CODE = {
  obesity: {
    data: {
      code: 'obesity',
      name: 'Obesity',
      meaning: 'Excess body fat accumulation that can increase long-term cardio-metabolic risk.',
      unit: 'cm',
      risk_score_scaled: 12,
      lifestyle_contribution: 24,
      disease_percentile: 88,
      lower_range_male: 1.0,
      higher_range_male: 2.0,
      lower_range_female: 1.0,
      higher_range_female: 2.0,
      causes_when_high: 'Sedentary routine, calorie surplus, poor sleep quality, high stress',
      causes_when_low: 'Balanced nutrition, regular movement, stable sleep and stress recovery',
      effects_when_high: 'Higher risk of insulin resistance, fatty liver, and blood-pressure burden.',
      effects_when_low: 'Supports better hormonal balance, energy, and long-term metabolic health.',
      what_to_do_when_low: 'Maintain current habits and continue periodic activity, protein intake, and sleep discipline.',
      what_to_do_when_high: 'Increase activity volume, optimize protein and fiber intake, improve sleep timing, and reduce ultra-processed foods.',
    },
    meta: {},
  },
  oxidative_stress: {
    data: {
      code: 'oxidative_stress',
      name: 'Oxidative Stress',
      meaning: 'When harmful molecules damage cells faster than the body can repair them.',
      unit: 'cm',
      risk_score_scaled: 27,
      lifestyle_contribution: null,
      disease_percentile: 2,
      lower_range_male: 1.0,
      higher_range_male: 2.0,
      lower_range_female: 2.0,
      higher_range_female: 3.0,
      causes_when_high: 'smoking, poor diet, pollution, stress',
      causes_when_low: 'smoking, poor diet, pollution, stress',
      effects_when_high: 'Cell damage and increased risk of chronic diseases.',
      effects_when_low: 'Cell damage and increased risk of chronic diseases.',
      what_to_do_when_low: 'Maintain a nutrient-dense diet rich in plant foods, stay active, and reduce exposure to environmental toxins where possible.',
      what_to_do_when_high: 'Increase intake of antioxidant-rich foods such as fruits, vegetables, nuts, and seeds. Stay physically active, improve sleep quality, manage stress, and avoid tobacco or excessive processed foods.',
    },
    meta: {},
  },
  pcos: {
    data: {
      code: 'pcos',
      name: 'PCOS',
      meaning: 'Hormonal and metabolic imbalance associated with irregular ovulation and insulin resistance.',
      unit: 'index',
      risk_score_scaled: 46,
      lifestyle_contribution: 58,
      disease_percentile: 64,
      lower_range_male: 0.0,
      higher_range_male: 0.0,
      lower_range_female: 1.0,
      higher_range_female: 2.0,
      causes_when_high: 'Insulin resistance, central adiposity, sleep disruption, chronic stress',
      causes_when_low: 'Improved insulin sensitivity, consistent sleep, and structured physical activity',
      effects_when_high: 'Can affect menstrual regularity, skin health, fertility, and weight trajectory.',
      effects_when_low: 'Supports better cycle regularity, hormonal balance, and metabolic resilience.',
      what_to_do_when_low: 'Continue insulin-sensitive eating, resistance training, and stress-management habits.',
      what_to_do_when_high: 'Prioritize strength training, increase daily movement, reduce high-glycemic load meals, and improve sleep consistency.',
    },
    meta: {},
  },
  hypertension: {
    data: {
      code: 'hypertension',
      name: 'Hypertension',
      meaning: 'Sustained high blood pressure that increases strain on heart and blood vessels over time.',
      unit: 'mmHg risk index',
      risk_score_scaled: 16,
      lifestyle_contribution: 28,
      disease_percentile: 86,
      lower_range_male: 1.0,
      higher_range_male: 2.0,
      lower_range_female: 1.0,
      higher_range_female: 2.0,
      causes_when_high: 'High sodium intake, inactivity, poor sleep, chronic stress',
      causes_when_low: 'Active lifestyle, adequate potassium intake, healthy weight, quality sleep',
      effects_when_high: 'Elevates long-term risk for stroke, kidney dysfunction, and cardiac load.',
      effects_when_low: 'Supports vascular flexibility and healthier long-term cardiovascular outcomes.',
      what_to_do_when_low: 'Maintain regular activity, hydration, and a minimally processed diet pattern.',
      what_to_do_when_high: 'Lower sodium load, improve cardio fitness, target healthy body composition, and monitor blood pressure trends.',
    },
    meta: {},
  },
  nafld: {
    data: {
      code: 'nafld',
      name: 'NAFLD',
      meaning: 'Fat accumulation in the liver unrelated to alcohol, often linked to metabolic stress.',
      unit: 'index',
      risk_score_scaled: 49,
      lifestyle_contribution: 63,
      disease_percentile: 52,
      lower_range_male: 1.0,
      higher_range_male: 2.0,
      lower_range_female: 1.0,
      higher_range_female: 2.0,
      causes_when_high: 'Insulin resistance, excess visceral fat, high fructose intake, inactivity',
      causes_when_low: 'Improved insulin function, weight control, and lower liver fat burden',
      effects_when_high: 'Can progress to liver inflammation, reduced metabolic health, and fatigue.',
      effects_when_low: 'Supports healthier liver enzymes and better glucose-lipid balance.',
      what_to_do_when_low: 'Continue active lifestyle and maintain balanced intake of protein, fiber, and healthy fats.',
      what_to_do_when_high: 'Aim for gradual fat loss, reduce sugary beverages and ultra-processed foods, and maintain regular exercise.',
    },
    meta: {},
  },
  cardiac_health: {
    data: {
      code: 'cardiac_health',
      name: 'Cardiac Health',
      meaning: 'Represents overall cardiovascular resilience based on combined metabolic and inflammatory signals.',
      unit: 'index',
      risk_score_scaled: 12,
      lifestyle_contribution: 22,
      disease_percentile: 90,
      lower_range_male: 1.0,
      higher_range_male: 2.0,
      lower_range_female: 1.0,
      higher_range_female: 2.0,
      causes_when_high: 'Elevated inflammation, poor lipid profile, inactivity, tobacco exposure',
      causes_when_low: 'Consistent movement, stable lipid profile, anti-inflammatory dietary pattern',
      effects_when_high: 'Increases long-term risk burden for coronary and vascular complications.',
      effects_when_low: 'Supports stronger endurance, better circulation, and lower risk trajectory.',
      what_to_do_when_low: 'Maintain heart-healthy behaviors including regular cardio and nutrient-dense meals.',
      what_to_do_when_high: 'Increase aerobic activity, optimize sleep and stress control, and improve fat quality in diet.',
    },
    meta: {},
  },
  thyroid_health: {
    data: {
      code: 'thyroid_health',
      name: 'Thyroid Health',
      meaning: 'Reflects how thyroid-regulated metabolism and hormonal signaling are tracking over time.',
      unit: 'index',
      risk_score_scaled: 12,
      lifestyle_contribution: 20,
      disease_percentile: 92,
      lower_range_male: 1.0,
      higher_range_male: 2.0,
      lower_range_female: 1.0,
      higher_range_female: 2.0,
      causes_when_high: 'Nutrient deficits, chronic stress, autoimmune load, poor recovery routines',
      causes_when_low: 'Stable nutrient intake, stress control, and healthy sleep-wake rhythm',
      effects_when_high: 'May influence energy, temperature regulation, mood, and body composition.',
      effects_when_low: 'Supports steady energy output and balanced metabolic function.',
      what_to_do_when_low: 'Continue nutrient-rich eating pattern and consistent sleep schedule.',
      what_to_do_when_high: 'Review iodine/selenium-rich intake, improve stress recovery, and monitor thyroid panel trends with clinician guidance.',
    },
    meta: {},
  },
  dyslipidemia: {
    data: {
      code: 'dyslipidemia',
      name: 'Dyslipidemia',
      meaning: 'Unfavorable blood lipid distribution that may increase vascular risk when persistent.',
      unit: 'index',
      risk_score_scaled: 21,
      lifestyle_contribution: 36,
      disease_percentile: 76,
      lower_range_male: 1.0,
      higher_range_male: 2.0,
      lower_range_female: 1.0,
      higher_range_female: 2.0,
      causes_when_high: 'High refined-fat/sugar pattern, inactivity, stress, inadequate sleep',
      causes_when_low: 'Balanced fats, high-fiber intake, activity consistency, healthy weight',
      effects_when_high: 'Can accelerate arterial plaque risk and affect long-term cardiac outcomes.',
      effects_when_low: 'Supports better vascular health and cardiometabolic protection.',
      what_to_do_when_low: 'Maintain current habits emphasizing fiber, omega-3 sources, and daily movement.',
      what_to_do_when_high: 'Reduce trans/saturated fat excess, improve exercise volume, and optimize waist management.',
    },
    meta: {},
  },
  diabetes: {
    data: {
      code: 'diabetes',
      name: 'Type 2 diabetes',
      meaning: 'Metabolic condition where insulin action weakens and blood-glucose control deteriorates over time.',
      unit: 'index',
      risk_score_scaled: 14,
      lifestyle_contribution: 26,
      disease_percentile: 85,
      lower_range_male: 1.0,
      higher_range_male: 2.0,
      lower_range_female: 1.0,
      higher_range_female: 2.0,
      causes_when_high: 'Insulin resistance, sedentary pattern, central adiposity, high glycemic diet',
      causes_when_low: 'Stable glucose regulation, active routine, and healthier body composition',
      effects_when_high: 'Long-term elevations can affect nerve, kidney, and cardiovascular systems.',
      effects_when_low: 'Supports sustained glucose control and better energy stability.',
      what_to_do_when_low: 'Continue resistance training, post-meal movement, and balanced meal timing.',
      what_to_do_when_high: 'Prioritize low-glycemic meals, strength training, weight management, and routine glucose monitoring.',
    },
    meta: {},
  },
};

export const buildRiskAnalysisDemoFallbackDetail = ({ diseaseCode = '', diseaseName = '-', riskScore = 0 }) => ({
  data: {
    code: diseaseCode,
    name: diseaseName,
    meaning: `${diseaseName} reflects one part of your preventive-risk profile and is shown here in demo mode.`,
    unit: null,
    risk_score_scaled: riskScore,
    lifestyle_contribution: 30,
    disease_percentile: 70,
    lower_range_male: null,
    higher_range_male: null,
    lower_range_female: null,
    higher_range_female: null,
    causes_when_high: 'Diet quality, stress load, sleep disruption, and low physical activity',
    causes_when_low: 'Consistent healthy lifestyle and better recovery patterns',
    effects_when_high: 'Persistent elevation may increase long-term health risk if unaddressed.',
    effects_when_low: 'Lower risk supports better preventive-health outlook over time.',
    what_to_do_when_low: 'Maintain current healthy routines and continue periodic monitoring.',
    what_to_do_when_high: 'Focus on activity, sleep, nutrition quality, and stress control to improve this score.',
  },
  meta: {},
});
