export const DEMO_HOMEPAGE_OVERVIEW_RESPONSE = {
  data: {
    assessment_id: 8,
    metabolic_age: 27.0,
    positive_wins: {
      low_risk: [
        {
          code: 'thyroid_health',
          name: 'Thyroid Health',
          risk_status: 'Healthy',
          risk_score_scaled: 7,
        },
        {
          code: 'diabetes',
          name: 'Type 2 diabetes',
          risk_status: 'Healthy',
          risk_score_scaled: 20,
        },
        {
          code: 'nafld',
          name: 'NAFLD',
          risk_status: 'Healthy',
          risk_score_scaled: 21,
        },
      ],
      healthy_habits: [],
      healthy_profiles: ['Complete Hemogram', 'Kidney Function with K', 'Liver Profile'],
    },
    risk_analysis: [
      {
        code: 'oxidative_stress',
        name: 'Oxidative Stress',
        risk_status: 'Increased',
        risk_score_scaled: 33,
        healthy_percentile: 98,
      },
      {
        code: 'nafld',
        name: 'NAFLD',
        risk_status: 'Healthy',
        risk_score_scaled: 21,
        healthy_percentile: 87,
      },
      {
        code: 'diabetes',
        name: 'Type 2 diabetes',
        risk_status: 'Healthy',
        risk_score_scaled: 20,
        healthy_percentile: 43,
      },
    ],
  },
  meta: {},
};

export const DEMO_HOMEPAGE_BLOOD_PARAMETERS_RESPONSE = {
  data: [
    {
      group_name: 'Liver Profile',
      test_count: 12,
      tests: [
        { test_id: 23, test_name: 'Albumin', parameter_key: 'albumin', unit: 'g/dL', value: 4.3, lower_range: 3.5, higher_range: 5.2 },
        { test_id: 36, test_name: 'Alkaline Phosphatase', parameter_key: 'alkaline_phosphatase', unit: 'U/L', value: 95.0, lower_range: 100.0, higher_range: 110.0 },
        { test_id: 19, test_name: 'Bilirubin Direct', parameter_key: 'bilirubin_direct', unit: 'mg/dL', value: null, lower_range: 0.0, higher_range: 0.2 },
        { test_id: 18, test_name: 'Bilirubin Total', parameter_key: 'bilirubin_total', unit: 'mg/dL', value: null, lower_range: 0.3, higher_range: 1.2 },
        { test_id: 21, test_name: 'GGPT', parameter_key: 'ggpt_value', unit: 'U/L', value: null, lower_range: 5.0, higher_range: 55.0 },
        { test_id: 37, test_name: 'Proteins Serum', parameter_key: 'proteins_serum', unit: null, value: null, lower_range: null, higher_range: null },
        { test_id: 15, test_name: 'SGOT (AST)', parameter_key: 'sgot_ast', unit: 'U/L', value: null, lower_range: 3.0, higher_range: 50.0 },
        { test_id: 16, test_name: 'SGPT (ALT)', parameter_key: 'sgpt_alt', unit: 'U/L', value: null, lower_range: 3.0, higher_range: 50.0 },
        { test_id: 20, test_name: 'Bilirubin Indirect', parameter_key: 'bilirubin_indirect', unit: 'mg/dL', value: null, lower_range: 0.0, higher_range: 0.8 },
        { test_id: 24, test_name: 'Globulin', parameter_key: 'globulin', unit: 'g/dL', value: 3.1, lower_range: 3.0, higher_range: 4.2 },
        { test_id: 25, test_name: 'A/G Ratio', parameter_key: 'a_g_ratio', unit: null, value: null, lower_range: 1.2, higher_range: 2.5 },
        { test_id: 38, test_name: 'SGOT/SGPT Ratio', parameter_key: 'sgot/sgpt_ratio', unit: 'ratio', value: null, lower_range: 0.7, higher_range: 1.4 },
      ],
    },
    {
      group_name: 'Kidney Function with K',
      test_count: 12,
      tests: [
        { test_id: 29, test_name: 'BUN Urea Nitrogen', parameter_key: 'bun_urea_nitrogen', unit: 'mg/dL', value: null, lower_range: 8.0, higher_range: 20.0 },
        { test_id: 39, test_name: 'Calcium Total', parameter_key: 'calcium_total', unit: null, value: null, lower_range: null, higher_range: null },
        { test_id: 40, test_name: 'Chlorides', parameter_key: 'chlorides', unit: null, value: null, lower_range: null, higher_range: null },
        { test_id: 26, test_name: 'Creatinine', parameter_key: 'creatinine', unit: 'mg/dL', value: 1.07, lower_range: 0.6, higher_range: 1.6 },
        { test_id: 41, test_name: 'Sodium', parameter_key: 'sodium', unit: null, value: null, lower_range: null, higher_range: null },
        { test_id: 42, test_name: 'Urea', parameter_key: 'urea', unit: 'mg/dl', value: null, lower_range: 17.0, higher_range: 43.0 },
        { test_id: 28, test_name: 'Uric Acid', parameter_key: 'uric_acid', unit: 'mg/dL', value: 6.2, lower_range: 3.5, higher_range: 7.2 },
        { test_id: 43, test_name: 'BUN/Creatinine Ratio', parameter_key: 'bun/creatinine_ratio', unit: null, value: null, lower_range: null, higher_range: null },
        { test_id: 44, test_name: 'Urea/Creatinine Ratio', parameter_key: 'urea/creatinine_ratio', unit: 'Ratio', value: null, lower_range: null, higher_range: null },
        { test_id: 27, test_name: 'EGFR', parameter_key: 'egfr', unit: null, value: null, lower_range: 90.0, higher_range: 999.0 },
        { test_id: 45, test_name: 'Phosphorus Inorganic', parameter_key: 'phosphorus_inorganic', unit: null, value: null, lower_range: null, higher_range: null },
        { test_id: 46, test_name: 'Potassium', parameter_key: 'potassium', unit: null, value: null, lower_range: null, higher_range: null },
      ],
    },
    {
      group_name: 'Thyroid Profile',
      test_count: 3,
      tests: [
        { test_id: 47, test_name: 'T3', parameter_key: 't3', unit: 'ng/ml', value: null, lower_range: 0.87, higher_range: 1.78 },
        { test_id: 48, test_name: 'T4', parameter_key: 't4', unit: 'ug/dl', value: null, lower_range: 5.48, higher_range: 14.28 },
        { test_id: 49, test_name: 'TSH', parameter_key: 'tsh', unit: 'uIU/mL', value: null, lower_range: 0.38, higher_range: 5.33 },
      ],
    },
    {
      group_name: 'Iron Studies',
      test_count: 4,
      tests: [
        { test_id: 50, test_name: 'Iron Serum', parameter_key: 'iron_serum', unit: 'ug/dl', value: null, lower_range: 70.0, higher_range: 180.0 },
        { test_id: 51, test_name: 'TIBC', parameter_key: 'tibc', unit: 'ug/dl', value: null, lower_range: 250.0, higher_range: 400.0 },
        { test_id: 52, test_name: 'UBIC', parameter_key: 'ubic', unit: null, value: null, lower_range: null, higher_range: null },
        { test_id: 53, test_name: 'Transferrin Saturation', parameter_key: 'transferrin_saturation', unit: '%', value: null, lower_range: 10.0, higher_range: 50.0 },
      ],
    },
    {
      group_name: 'Lipid Profile',
      test_count: 9,
      tests: [
        { test_id: 30, test_name: 'Cholesterol Total', parameter_key: 'cholesterol_total', unit: 'mg/dL', value: null, lower_range: 0.0, higher_range: 200.0 },
        { test_id: 32, test_name: 'HDL Cholestrol Direct', parameter_key: 'hdl_cholestrol_direct', unit: 'mg/dL', value: null, lower_range: 40.0, higher_range: 60.0 },
        { test_id: 33, test_name: 'Triglycerides', parameter_key: 'triglycerides', unit: 'mg/dL', value: null, lower_range: 0.0, higher_range: 150.0 },
        { test_id: 34, test_name: 'Non-HDL Cholestrol', parameter_key: 'non_hdl_cholestrol', unit: 'mg/dL', value: null, lower_range: 0.0, higher_range: 160.0 },
        { test_id: 35, test_name: 'CHOL/HDL Ratio', parameter_key: 'chol_hdl_ratio', unit: null, value: null, lower_range: 0.0, higher_range: 4.4 },
        { test_id: 31, test_name: 'LDL Cholestrol', parameter_key: 'ldl_cholestrol', unit: 'mg/dL', value: null, lower_range: 0.0, higher_range: 100.0 },
        { test_id: 55, test_name: 'VLDL Cholestrol', parameter_key: 'vldl_cholestrol', unit: null, value: null, lower_range: null, higher_range: null },
        { test_id: 56, test_name: 'LDL/HDL Cholestrol', parameter_key: 'ldl/hdl_cholestrol', unit: null, value: null, lower_range: null, higher_range: null },
        { test_id: 57, test_name: 'HDL/LDL Cholestrol Ratio', parameter_key: 'hdl/ldl_cholestrol_ratio', unit: null, value: null, lower_range: null, higher_range: null },
      ],
    },
    {
      group_name: 'Complete Hemogram',
      test_count: 25,
      tests: [
        { test_id: 68, test_name: 'Absolute Basophils Count', parameter_key: 'absolute_basophils_count', unit: null, value: null, lower_range: null, higher_range: null },
        { test_id: 69, test_name: 'Absolute Eosinophils Count', parameter_key: 'absolute_eosinophils_count', unit: '10^3/uL', value: null, lower_range: 0.04, higher_range: 0.44 },
        { test_id: 70, test_name: 'Absolute Lymphocyte Count', parameter_key: 'absolute_lymphocyte_count', unit: '10^3/uL', value: null, lower_range: 1.4, higher_range: 3.5 },
        { test_id: 71, test_name: 'Absolute Monocyte Count', parameter_key: 'absolute_monocyte_count', unit: '10^3/uL', value: null, lower_range: 0.2, higher_range: 1.0 },
        { test_id: 72, test_name: 'Absolute Neutrophil Count', parameter_key: 'absolute_neutrophil_count', unit: '10^3/uL', value: null, lower_range: 4.0, higher_range: 10.0 },
        { test_id: 73, test_name: 'ESR Automated', parameter_key: 'esr_automated', unit: null, value: null, lower_range: null, higher_range: null },
        { test_id: 1, test_name: 'Hemoglobin Hb', parameter_key: 'hemoglobin', unit: 'g/dL', value: null, lower_range: 13.0, higher_range: 17.0 },
        { test_id: 5, test_name: 'MCH', parameter_key: 'mch', unit: 'pg', value: null, lower_range: 27.0, higher_range: 32.0 },
        { test_id: 6, test_name: 'MCHC', parameter_key: 'mchc', unit: 'g/dL', value: null, lower_range: 31.5, higher_range: 34.5 },
        { test_id: 4, test_name: 'MCV', parameter_key: 'mcv', unit: 'fL', value: null, lower_range: 83.0, higher_range: 101.0 },
        { test_id: 74, test_name: 'MPV Mean Platelate Count', parameter_key: 'mpv_mean_platelate_count', unit: 'fL', value: null, lower_range: 7.0, higher_range: 9.0 },
        { test_id: 75, test_name: 'PCV Hematocrit', parameter_key: 'pcv_hematocrit', unit: '%', value: null, lower_range: null, higher_range: null },
        { test_id: 8, test_name: 'Platelate Count', parameter_key: 'platelate_count', unit: 'thousand/uL', value: null, lower_range: 150.0, higher_range: 410.0 },
        { test_id: 9, test_name: 'WBC', parameter_key: 'wbc', unit: 'thousand/uL', value: null, lower_range: 4.0, higher_range: 10.0 },
        { test_id: 7, test_name: 'RDW', parameter_key: 'rdw', unit: '%', value: null, lower_range: 11.6, higher_range: 14.0 },
        { test_id: 10, test_name: 'Neutrophils', parameter_key: 'neutrophils', unit: '%', value: 71.5, lower_range: 40.0, higher_range: 80.0 },
        { test_id: 13, test_name: 'Eosinophils', parameter_key: 'eosinophils', unit: '%', value: 3.1, lower_range: 1.0, higher_range: 6.0 },
        { test_id: 11, test_name: 'Lymphocytes', parameter_key: 'lymphocytes', unit: '%', value: 18.5, lower_range: 20.0, higher_range: 40.0 },
        { test_id: 12, test_name: 'Monocytes', parameter_key: 'monocytes', unit: '%', value: 4.6, lower_range: 2.0, higher_range: 10.0 },
        { test_id: 14, test_name: 'Basophils', parameter_key: 'basophils', unit: '%', value: 0.8, lower_range: 0.0, higher_range: 2.0 },
        { test_id: 76, test_name: 'RDW-CV', parameter_key: 'rdw-cv', unit: null, value: null, lower_range: null, higher_range: null },
        { test_id: 77, test_name: 'RCC', parameter_key: 'rcc', unit: null, value: null, lower_range: null, higher_range: null },
        { test_id: 2, test_name: 'Red blood cells', parameter_key: 'red_blood_cells', unit: 'million/uL', value: null, lower_range: 4.5, higher_range: 5.5 },
        { test_id: 78, test_name: 'GK Index', parameter_key: 'gk_index', unit: null, value: null, lower_range: null, higher_range: null },
        { test_id: 79, test_name: 'MENTZER Index 9 MCV', parameter_key: 'mentzer_index_9mcv', unit: 'Ratio', value: null, lower_range: null, higher_range: null },
      ],
    },
    {
      group_name: 'Vitamin Profile',
      test_count: 2,
      tests: [
        { test_id: 58, test_name: 'Vitamin B12', parameter_key: 'vitamin_b12', unit: 'pg/mL', value: 283.0, lower_range: 222.0, higher_range: 1439.0 },
        { test_id: 59, test_name: 'Vitamin D Total-25 Hydroxy', parameter_key: 'vitamin_d_total-25_hydroxy', unit: 'ng/ml', value: null, lower_range: 30.0, higher_range: 100.0 },
      ],
    },
    {
      group_name: 'Diabetes Profile',
      test_count: 3,
      tests: [
        { test_id: 60, test_name: 'Fasting Sugar', parameter_key: 'fasting_sugar', unit: null, value: null, lower_range: null, higher_range: null },
        { test_id: 62, test_name: 'Glycated hemoglobin', parameter_key: 'glcated_hemoglobin', unit: null, value: null, lower_range: null, higher_range: null },
        { test_id: 63, test_name: 'Average Blood Glucose', parameter_key: 'average_blood_glucose', unit: null, value: null, lower_range: null, higher_range: null },
      ],
    },
  ],
  meta: {},
};
